class message_types:
    pass
    es_types = {
        'A' : 'Account  Details  Message',
        'B' : 'Override Account Message or Broadcast Order Flow Message',
        'C' : 'Customer Account ID List Message or Customer Account Message',
        'D' : 'AWAY MPID List Message',
        'E' : 'Server - To - Client Test Request or Firm Channel List Message',
        'F' : 'Threshold / Easy-To-Borrow List Request Message or Threshold/Easy To Borrow List Message or Account Sell Mode Message or Symbol Max Shares Per Account Message or Account Restriction / Max Dollar-Share per Order Message:',
        'G' : 'Cancel / Replace Order Request',
        'H' : 'Heartbeat Message',
        'I' : 'Administrative Message, Login Response Message',
        'J' : '',
        'K' : '',
        'L' : 'Link status Message',
        'M' : 'Combined LOCATE and New Order / Can / Repl Message',
        'N' : 'Order Request Message or Cancel Request Message',
        'O' : 'Logout Message',
        'P' : 'Overnight Open Position Message',
        'Q' : '',
        'R' : '',
        'S' : 'Login Response or Order Details Message(New Order / Order Status) or Order Rejected Messages',
        'T' : 'Response Messages/Token Message',
        'U' : 'Login End Message',
        'V' : '',
        'W' : 'Ticket Messages:',
        'X' : 'Channel Redirection Information Message',
        'Y' : '',
        'Z' : 'Error Messages'
    }

    is_types = {
        '1': 'Level 1 Data Request or Stop Receiving Level 1 Data',
        '2': 'Level 2 Data Request or Stop Receiving Level 2 Data',
        '3': 'ECN Book Data Request or Stop Receiving ECN Book Data',
        '4': 'Time and Sale (Prints) Data Request or Stop Receiving Time and Sale (Prints) Data',
        '5': 'Prints History Request',
        '6': 'Fundamental Data Request',
        '7': 'Variable Data Request or Stop Receiving Variable Data',
        '8': 'Stop Receiving Trade Order Flow',
        '9': 'Variables data',
        '0': '',
        'A': 'Ask side update',
        'B': 'B for Bid side',
        'C': 'both A and B side changes',
        'D': 'Intraday Highs',
        'E': '',
        'F': 'Open Price',
        'G': 'Previous days Close',
        'H': 'Current Volume',
        'I': '',
        'J': 'When Last Trade has changed, this message is sent',
        'K': 'Intraday Lows',
        'L': 'Link Status Message',
        'M': '',
        'N': 'Todays (non-official) closing prices',
        'O': '',
        'P': '',
        'Q': '',
        'R': '',
        'S': '',
        'T': 'Response Messages/Token Message',
        'U': '',
        'V': 'VWAP Update',
        'W': '',
        'X': '',
        'Y': 'Text Message',
        'Z': ''
    }