class OrderStatusFields:
    OSF_MESSAGE_NUMBER = 1
    OSF_DETAIL_TYPE = 2
    OSF_DATE_TIME = 7
    OSF_ACCOUNT_ID = 8
    OSF_ORDER_ID = 9
    OSF_ORDER_SYMBOL = 10
    OSF_SIDE = 11
    OSF_QUANTITY = 12
    OSF_ORDER_PRICE = 13
    OSF_CHANNEL = 15
    OSF_TIF = 16
    OSF_ORDER_TYPE = 18
    OSF_HIDDEN_FLAG = 20
    OSF_PEG_TYPE = 21
    OSF_PEG_OFFSET = 22
    OSF_DISCRETIONARY_OFFSET = 23
    OSF_MAX_FLOOR_SHOW_SIZE = 24
    OSF_TICKET_ID = 25
    OSF_ALGO_DETAILS = 26
    OSF_ORIGINAL_SIDE = 27

